# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: Deploy to AWS

on:
  push:

env:
  IMAGE_PATH_AND_TAG: ghcr.io/sage-bionetworks/genie-bpc-shiny:0.1.0
  AWS_DEFAULT_REGION: 'us-east-1' 
  PORT: 3838
  COST_CENTER: "Genie-AACR BPC / 312100"
  STACK_NAME_PREFIX: genie-bpc-shiny
  HOST_NAME: genie-bpc.dev.sagebase.org
  HOSTED_ZONE_NAME: sagebase.org
  HOSTED_ZONE_ID: Z28CDXGXBHW4TT
  AWS_DEPLOYMENT_ROLE: arn:aws:iam::449435941126:role/meta-cdk-role
 

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
        # Authenticate to AWS using GitHub OIDC
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume:  ${{ env.AWS_DEPLOYMENT_ROLE }}
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 1200
          
        # https://github.com/marketplace/actions/aws-cdk-github-actions
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          working_dir: 'cdk'
        env:
          DOCKER_IMAGE: ${{ env.IMAGE_PATH_AND_TAG }}
 
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          working_dir: 'cdk'
          actions_comment: false
        env:
          DOCKER_IMAGE: ${{ env.IMAGE_PATH_AND_TAG }}
           